# Generated by Django 4.0.6 on 2023-11-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_content_alter_article_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
                ('is_common', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='word_frequencies',
            field=models.JSONField(default=dict),
        ),
    ]
